spring:
  application:
    name: anabada

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.anabada: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

cloud:
  aws:
    credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}s
    region:
      static: ap-southeast-2
    s3:
      bucket: anabada-images
    stack:
      auto: false

email-auth:
  code-ttl: 300
  verified-ttl: 600
  code-length: 6